### ISSUE TITLE
Imports not showing

### ISSUE THREAD

**Issue by tweakimp** [lejsue/symbols-navigator#11]
I have this python code:
```python
from random import choice

x = [1, 2, 3, 4]

def printChoice(var):
    print(choice(var))

printChoice(x)
```
The navigator only shows: `var x` and `f(x) printChoice(var)`, but no `import`.

When I change the first line to
```python
from random import choice as choice
```
the navigator shows: `choice`, but with no icon.

**Comment by lejsue** [comment]
I guess it is due to unknow type of symbol. Let me check it, and add the new type into package.

**Comment by tweakimp** [comment]
It would also be cool if there was a different icon for an import from the standard library :)

**Comment by lejsue** [comment]
Hi,
Sorry for my late reply.
I checked the issue list of universal-ctag, and found that there is an explanation about this situation.
https://github.com/universal-ctags/ctags/issues/683#issuecomment-167046668
Based on this document, "choice" will be an unknown kind, therefore I add an "unknown" icon for this situation. 
Hope it is ok with you.  :D
