### ISSUE TITLE
Python import … as statement within method breaks listing.

### ISSUE THREAD

**Issue by mjstahlberg** [lejsue/symbols-navigator#13]
Hello, I noticed some weird behaviour when class methods contain an `import modulename as newname` statement. The code
```
class TestClass:
    def method(self):
        pass

    def methodWithImport(self):
        import numpy as np

    def secondMethod(self):
        pass

    def secondMethodWithImport(self):
        import numpy as np
```
produces (with my local `ctags` from https://github.com/universal-ctags/ctags) the tags
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_OUTPUT_MODE	u-ctags	/u-ctags or e-ctags/
!_TAG_PROGRAM_AUTHOR	Universal Ctags Team	//
!_TAG_PROGRAM_NAME	Universal Ctags	/Derived from Exuberant Ctags/
!_TAG_PROGRAM_URL	https://ctags.io/	/official site/
!_TAG_PROGRAM_VERSION	0.0.0	/8e098045/
TestClass	test.py	/^class TestClass:$/;"	c
method	test.py	/^    def method(self):$/;"	m	class:TestClass
methodWithImport	test.py	/^    def methodWithImport(self):$/;"	m	class:TestClass
np	test.py	/^        import numpy as np$/;"	I	member:TestClass.methodWithImport	file:
np	test.py	/^        import numpy as np$/;"	I	member:TestClass.secondMethodWithImport	file:
secondMethod	test.py	/^    def secondMethod(self):$/;"	m	class:TestClass
secondMethodWithImport	test.py	/^    def secondMethodWithImport(self):$/;"	m	class:TestClass
```
which, according to an response to my original issue report at universal-ctags/ctags#1731, are correct. However, symbols-navigator produces the following bad listing:

![A broken listing](http://dl.viech.name/ctagsissue.jpg)

**Comment by lejsue** [comment]
Hi,
Sorry for the late reply, and thanks for your report! It is a bug for type assignment in symbols-navigator, especially in Python language.
I already fixed it, now it will show as this.
![2018-08-23 9 51 06](https://user-images.githubusercontent.com/9697224/44500322-9e042600-a6ba-11e8-9516-d9732466ec74.png)
