### ISSUE TITLE
symbols tab appears to crash and is empty

### ISSUE THREAD

**Issue by joachim-n** [lejsue/symbols-navigator#14]
I occasionally have a problem where the symbols tab is completely empty. Hiding it and opening it again doesn't fix it.

It also appears empty if I open a new file in the same window. Opening a new project in a new window shows the symbols OK though.

**Comment by lejsue** [comment]
Hi @joachim-n ,
Do you still have this issue? Since I just test it, not found the problem. I open a new file and code something in it, then save it, and then there are some symbols on the symbols-navigator tree.

**Comment by joachim-n** [comment]
Hi
I've stopped using Atom and switched to VS Code. Atom was just too buggy and would slow my machine down or crash. 
Thanks for all your work on this plugin though, it was really useful!

**Comment by lejsue** [comment]
Hi,
haha, no problem! I currently both use Atom and VS Code on my work, the system usage of VS Code is really less than Atom. lol
