### ISSUE TITLE
Has Trouble Analyzing Traits

### ISSUE THREAD

**Issue by mikebronner** [lejsue/symbols-navigator#19]
Not all methods and properties are shown for traits.

**Comment by lejsue** [comment]
Hi mikebronner,

Would you use 1.5.0 version? If so, there is a bug in this version. I fixed it in 1.5.1.
If not, could you please share me your sample code, and then I can check what happened.

Thanks!

**Comment by mikebronner** [comment]
Looks like it will take a while before 1.5.1 makes it to the atom package repository. I'll check as soon as it updates. (Been refreshing updates for the past 10 minutes, but it seems to take more time than that to get picked up there.) Thanks @lejsue !

**Update:** looks like you removed the 1.5.1 version? I'll check as soon as it's out. :)

**Comment by mikebronner** [comment]
Version 1.5.1 fixes the issue. Thanks!
