### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by delputnam** [lejsue/symbols-navigator#2]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (<embedded>:1684:11)
SymbolsNavigatorView.generateTags (/Users/delputnam/.atom/packages/symbols-navigator/lib/symbols-navigator-view.js:134:79)
<unknown> (/Users/delputnam/.atom/packages/symbols-navigator/lib/symbols-navigator-view.js:91:20)
SymbolsNavigatorView.populate (/Users/delputnam/.atom/packages/symbols-navigator/lib/symbols-navigator-view.js:110:11)
<unknown> (/Users/delputnam/.atom/packages/symbols-navigator/lib/symbols-navigator-view.js:63:13)
Function.module.exports.Emitter.simpleDispatch (<embedded>:63446:20)
```

**Comment by lejsue** [comment]
Hi delputnam, 

Thanks for your report.

In 0.1.0 version, I used two dependencies, i.e. Q and atom-space-pen-views, but they are deprecated. 
Therefore, I removed them in 1.0.0 version and used new packages. It should be no any deprecated warning.
But there is still here. I don't know why, I'll check how to fix them.

**Comment by lejsue** [comment]
lol....

Sorry, I found where is the problem. I forget to change done() to then().
I'll fix it in next release.
