### ISSUE TITLE
Functions with parameters are not visible in symbols list after upgrading to version 1.5.0

### ISSUE THREAD

**Issue by oqolopo** [lejsue/symbols-navigator#20]
After update from 1.4.0 to version 1.5.0 at least PHP functions with parameters are invisible in symbols list. There are only function with no parameters.

**Comment by lejsue** [comment]
Hi oqolopo,

Thanks for reporting it. Yes, it is a bug, I fixed it in v1.5.1, please update to v.1.5.1, and see if it is ok now.

Thanks!

**Comment by oqolopo** [comment]
Everything is OK now. Thank you!
