### ISSUE TITLE
Functions with specific optional parameters do not appear in the symbols list.

### ISSUE THREAD

**Issue by oqolopo** [lejsue/symbols-navigator#22]
First of all, sincere thanks for your really useful tool and the attention paid!
Recently I noticed that functions with optional arguments having default value enclosed in single or double quotes do not appear in the symbols list.
Thanks again for your time!

**Comment by lejsue** [comment]
Hi oqolop,
XaverKlemenschits help to fix this issue, please see if it is ok now!
