### ISSUE TITLE
How do I define custom file types

### ISSUE THREAD

**Issue by stibinator** [lejsue/symbols-navigator#25]
I'm doing working on an arduino project which uses c++ grammar, but with the file extension .ino. So symbols-navigator doesn't work. How do I tell symbols navigator to treat .ino files as c++? 

I've worked around the issue by defining .ino files as language.cpp in my core configs, but that means that any arduino specific tools no longer work.

**Comment by lejsue** [comment]
Hi stibinator,
Sorry for that, in the current version, you cannot customize file types.
Let me see how to add this new feature soon.

**Comment by lejsue** [comment]
Hi stibinator,
I just found a bug on symbols-navigator, I'll fix it and tag a new release today.

In symbols-navigator, I use the default grammer file type from Atom.
If the Atom recognizes .ino files as C++, and show "C++" on the status bar (as follwing screenshot),
then symbols-navigator will parse tags by using C++ language.
![status-bar](https://user-images.githubusercontent.com/9697224/44324020-c3a8e980-a486-11e8-9d52-db43c0f304b5.png)

Please let me know if you see it on your status bar, and if it is ok after you update symbols-navigator to the newest version.
