### ISSUE TITLE
Does not navigate to Python classes

### ISSUE THREAD

**Issue by NCRonB** [lejsue/symbols-navigator#28]
When clicking on a Python class symbol, the cursor does not move to that class.

**Comment by lejsue** [comment]
Hi,
Is the class symbol collapsible?
If yes, XaverKlemenschits helps to create a new config parameter, Collapse Click Type. It can change the behavior of collapsible item to collapse it or jump to the class.
I just published a new version for this new config.
Please try it! Thanks!

**Comment by NCRonB** [comment]
Yes, the class symbol is collapsible. The new Collapse Click Type setting of "Go to symbol" is exactly what I was looking for. Thank you!

**Comment by j2bbayle** [comment]
This issue can be closed, I believe :)
