### ISSUE TITLE
Single click

### ISSUE THREAD

**Issue by Michal-Mikolas** [lejsue/symbols-navigator#6]
Hello, 
the package works great so far :-) Is it possible to move cursor to the symbol by simple single-click in symbols panel? Now I have to use double-click. And single-click does nothing. 

Thank you :-)

**Comment by lejsue** [comment]
Hi,
It's a good suggestion, I think I can add an option of "single-click" and "double-click" in setting page, then you can change it.

**Comment by lejsue** [comment]
I already added the option in setting page, please let me know if it is good for you. :-)

**Comment by Michal-Mikolas** [comment]
Works great, my mouse is happier now :-D 

Thanks a lot for the extension :-)
