### ISSUE TITLE
Show current symbol in status bar?

### ISSUE THREAD

**Issue by ryanpcmcquen** [lejsue/symbols-navigator#7]
First off, thank you for this amazing plugin!

Is there a way to show the current symbol (wherever the cursor is) in the status bar? I really miss that functionality from TextMate. If not, that would be an amazing feature!

**Comment by lejsue** [comment]
Hi,

Thanks! I have not used TextMate before, but I remember that Atom supports an easy way to show something on status bar. So, please let me check how to implement it. :D

**Comment by ryanpcmcquen** [comment]
Thank you! It would be a killer feature for me.

**Comment by lejsue** [comment]
Hi,

I googled some screenshot of TextMate, but still not so clear.
I tried to make an example, please let me know if it is what you need.

![symbol_status_bar](https://user-images.githubusercontent.com/9697224/33986746-84050b02-e0f9-11e7-91b6-98bcc430caf5.PNG)

**Comment by ryanpcmcquen** [comment]
You are amazing! That is exactly what I was looking for!

**Comment by ryanpcmcquen** [comment]
For reference, here is a screenshot from TextMate:
http://shinworld.altervista.org/images/textmate_preview.png

Notice the `main` in the status bar. You implemented it beautifully! Any idea when it will be ready for release?

**Comment by lejsue** [comment]
Sorry to keep you waiting, I just released it. 
I added an option to enable this new feature. You can find it in the setting of symbols-navigator. 
If you checked "Show Current Symbol On Status Bar" to enable, you will see it!
I hope it can work well, please let me know if there is any bug! Thanks a lot!
